# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'SwiftGen'
  
  target 'MoviesUnitTests' do
      # use_frameworks!
      pod 'iOSSnapshotTestCase'
  end
  
end
